name: dotenv_gcp
channels:
  - anaconda
dependencies:
  - python=3.8
  - numpy>=1.19
  - pandas>=1.1
  - astropy>3.2.1
  - conda-forge::lightkurve
  - h5py>=2.10
  - conda-forge::pymc3
  - conda-forge::celerite
  - matplotlib>=3.3
  - seaborn>=0.11
  - pip
  - pip:
    - wandb
    - tqdm
    - mypy
    - corner
    - exoplanet==0.3.3
    - google-cloud-storage>1.16